# version: '3.9'

# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#     command: uvicorn app.main:app --host 0.0.0.0 --reload
#     volumes:
#       - .:/code

#   worker:
#     build: .
#     command: celery -A app.tasks worker --loglevel=info
#     depends_on:
#       - redis

#   beat:
#     build: .
#     command: celery -A app.tasks beat --loglevel=info
#     depends_on:
#       - redis

#   redis:
#     image: redis:7


version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  beat:
    build: .
    command: celery -A app.tasks.celery_app beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7
